### ISSUE TITLE
Endpoints are the beginning

### ISSUE THREAD

**Issue by aichholzer** [redcenter/api-design-tips#3]
> If you get more familiar with REST, you will see the idea behind this endpoint. The endpoint returns all products by default. If you only want a specific product based on an id (bad example 2), you add a filter for that attribute.

> Like this: /v1/products/?id=2345

Religiously speaking, this is not correct. REST expects the `productId` (in this case) to be a query parameter:

```
/v1/products/{productId}
```
```
/v1/products/2345
```

**Comment by redcenter** [comment]
You're right.
