### ISSUE TITLE
The expand parameter

### ISSUE THREAD

**Issue by aichholzer** [redcenter/api-design-tips#5]
This is entirely subjective and not something that should influence the design of your API.

```
{
       "status": 200,
       "id": "12345",
       "href": "https://api.domain.com/v1/orders/12345",
       "amount": 201.99,
       "customer": {
          "id": "54321",
          "href": "https://api.domain.com/v1/customer/54321"
       }
    }
```

The above would be the correct answer in any case. A good API gives users only what they need, hence if someone needs more information about the customer, he can make another API request to get it. This should be an issue -and a decision- to be dealt with internally, purely for performance reasons.

"Expanding" the customer will, most likely, involve multiple database queries or a `JOIN`. JOINS are not as cheap as one might think, so the more performant approach is probably to make two separate queries, when needed of course.

By the way, the `customer` URI is wrong, should be plural:

```
https://api.domain.com/v1/customers/54321
```

**Comment by redcenter** [comment]
You are right (about the endpoint).
